#!/bin/bash -l

# Activate environment for front-end and back-end
conda activate ends

# Run streamlit frontend to get user inputs - will be run on port 8501 by default
streamlit run './UI Files/wgs_ui_v2.py' --logger.level debug # for debugging

# Need section here for converting user inputs into samplesheet for WGS pipeline

# Activate conda environment for Nextflow and mitochondrial variant calling
conda deactivate && sleep 2
conda activate nf_mitvar

# Run Nextflow Mitochondrial Variant Calling Pipeline - takes ~4.5 min
OUTPUTDIR="results"
PROJECT="wgs_results"
nextflow run nf_integrated/Mito_WGS_Nextflow/Mitochondra_Variant_Call.nf --outdir ${OUTPUTDIR} --project ${PROJECT} # -resume

# Now run Nextflow mitoedit pipeline
INPUT_MTE_SEQ="nf_integrated/Mito_WGS_Nextflow/Nextflow_mitochondra_wgs/MT_bw/MT.fa"
INPUT_TAB="${OUTPUTDIR}/${PROJECT}/Annotate_MTDB_Parse_FinalizeTable/all.maf.fisher_annotated_gMafOrtMaf_greaterThanOrEqual0.03_withNewGroups_allColumns.txt"
nextflow run nf_integrated/nf_mte/mitoedit.nf --mtdna_seq_path ${INPUT_MTE_SEQ} \
    --input_tab ${INPUT_TAB} --output_prefix ${PROJECT} # --bystander_file ${BYSTANDER_INPUT} -resume

# Generate IGV config with BAM locations


# Add chrM to the first column of the mod_tab file generated by mitoedit 
# and then only get the necessary columns for igv-reports input
printf "Chr\tPos\tType\tSize\tCoverage\tNormal_MAF\tTumor_MAF\tRef_Allele\tAlt_Allele\tScore\n" > mod_tab.tsv
# Print Mito_WGS results to mod_tab.tsv - omit first line (header)
awk 'BEGIN{FS=OFS="\t"} {print "chrM",$0}' ${INPUT_TAB} | awk 'BEGIN{FS=OFS="\t"} NR>1{print $1,$13,$4,1,$16,$21,$20,$14,$15,$32}' >> mod_tab.tsv

# Deactivate conda environment for Nextflow
conda deactivate && sleep 2

# Activate conda environment for igv-reports
conda activate ends

# Run igv-reports to generate IGV report for mitochondrial variants
python3 ${CONDA_PREFIX}/lib/python3.13/site-packages/igv_reports/report.py ${OUTPUTDIR}/${PROJECT}/MitoEdit_${PROJECT}_final_variants_mod_tab.tsv ${INPUT_MTE_SEQ}  --sequence 1 --begin 2 --end 2 --info-columns Chr Pos Type Size Coverage Normal_MAF Tumor_MAF Ref_Allele Alt_Allele Score --flanking 500 --tracks https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/refGene.txt.gz --title "${PROJECT}" --output ${PROJECT}-MT.genome.html --track-config igv/igv.config

# cd /users/5/levin252/external_data/StJudes25-Team4/KIDS25-Team4
# python3 ${CONDA_PREFIX}/lib/python3.13/site-packages/igv_reports/report.py ../mod_tab.tsv nf_integrated/Mito_WGS_Nextflow/Nextflow_mitochondra_wgs/MT_bwa/MT.fa --sequence 1 --begin 2 --end 2 --info-columns Chr Pos Type Size Coverage Normal_MAF Tumor_MAF Ref_Allele Alt_Allele Score --flanking 500 --tracks https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/refGene.txt.gz --title "HG008" --output HG008-MT.genome.html --track-config ../igv.config
